[2022-04-18 15:28:20,187] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: xcom_dag.downloading_data 2022-04-17T00:00:00+00:00 [queued]>
[2022-04-18 15:28:20,389] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: xcom_dag.downloading_data 2022-04-17T00:00:00+00:00 [queued]>
[2022-04-18 15:28:20,392] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-04-18 15:28:20,393] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-04-18 15:28:20,396] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-04-18 15:28:20,530] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): downloading_data> on 2022-04-17T00:00:00+00:00
[2022-04-18 15:28:20,608] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'xcom_dag', 'downloading_data', '2022-04-17T00:00:00+00:00', '--job-id', '126', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/xcom_dag.py', '--cfg-path', '/tmp/tmp2nkzlmcj', '--error-file', '/tmp/tmp3fu5y_v8']
[2022-04-18 15:28:20,612] {standard_task_runner.py:52} INFO - Started process 3158 to run task
[2022-04-18 15:28:20,713] {standard_task_runner.py:77} INFO - Job 126: Subtask downloading_data
[2022-04-18 15:28:21,654] {logging_mixin.py:104} INFO - Running <TaskInstance: xcom_dag.downloading_data 2022-04-17T00:00:00+00:00 [running]> on host airflowvm
[2022-04-18 15:28:22,517] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=xcom_dag
AIRFLOW_CTX_TASK_ID=downloading_data
AIRFLOW_CTX_EXECUTION_DATE=2022-04-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-17T00:00:00+00:00
[2022-04-18 15:28:22,536] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-04-18 15:28:22,537] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-04-18 15:28:22,603] {subprocess.py:75} INFO - Output:
[2022-04-18 15:28:25,678] {subprocess.py:83} INFO - Command exited with return code 0
[2022-04-18 15:28:25,806] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=xcom_dag, task_id=downloading_data, execution_date=20220417T000000, start_date=20220418T152820, end_date=20220418T152825
[2022-04-18 15:28:26,052] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-04-18 15:28:26,109] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 3158
[2022-04-18 15:28:26,148] {taskinstance.py:1264} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-04-18 15:28:26,161] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2022-04-18 15:28:26,197] {process_utils.py:66} INFO - Process psutil.Process(pid=3158, status='terminated', exitcode=1, started='15:28:20') (3158) terminated with exit code 1
